services:
  stat-ee:
    image: stat-ee:latest
    ports:
      - '${PORT}:${PORT}'
    env_file: ".env"
    volumes:
      - ./certs:/home/appuser/stat-ee/certs
      - ./models:/home/appuser/stat-ee/models