
  CREATE TABLE "ELUJOULISUSEINDEKS"."AASTASED" 
   (	"jykood" VARCHAR2(255 BYTE), 
	"aasta" BINARY_DOUBLE, 
	"emtak" BINARY_DOUBLE, 
	"sektor_nr" BINARY_DOUBLE, 
	"sektor_txt" VARCHAR2(255 BYTE), 
	"klaster" VARCHAR2(255 BYTE), 
	"tarv_h" BINARY_DOUBLE, 
	"oig_vorm" VARCHAR2(255 BYTE), 
	"ettevotte_suurusklass" BINARY_DOUBLE, 
	"asu_kood" BINARY_DOUBLE, 
	"kov" BINARY_DOUBLE, 
	"maakond" BINARY_DOUBLE, 
	"kaibevarad" BINARY_DOUBLE, 
	"raha" BINARY_DOUBLE, 
	"lyhiajalised_nouded" BINARY_DOUBLE, 
	"lyhiajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"varud" BINARY_DOUBLE, 
	"pohivarad" BINARY_DOUBLE, 
	"pikaajalised_nouded" BINARY_DOUBLE, 
	"pikaajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"materiaalne_pohivara" BINARY_DOUBLE, 
	"immateriaalne_pohivara" BINARY_DOUBLE, 
	"varad_kokku" BINARY_DOUBLE, 
	"lyhiajalised_kohustused" BINARY_DOUBLE, 
	"lyhiajalised_volad" BINARY_DOUBLE, 
	"lyhiajalised_laenud" BINARY_DOUBLE, 
	"pikaajalised_kohustused" BINARY_DOUBLE, 
	"pikaajalised_volad" BINARY_DOUBLE, 
	"pikaajalised_laenud" BINARY_DOUBLE, 
	"kohustused_kokku" BINARY_DOUBLE, 
	"omakapital" BINARY_DOUBLE, 
	"kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"myygitulu" BINARY_DOUBLE, 
	"muud_aritulud" BINARY_DOUBLE, 
	"muud_arikulud" BINARY_DOUBLE, 
	"toojoukulud" BINARY_DOUBLE, 
	"arikasum" BINARY_DOUBLE, 
	"intressikulud" BINARY_DOUBLE, 
	"aruandeaasta_kasum" BINARY_DOUBLE, 
	"lvkk" BINARY_DOUBLE, 
	"mvk" BINARY_DOUBLE, 
	"rk" BINARY_DOUBLE, 
	"lllk" BINARY_DOUBLE, 
	"llvk" BINARY_DOUBLE, 
	"llok" BINARY_DOUBLE, 
	"vakk" BINARY_DOUBLE, 
	"lvkak" BINARY_DOUBLE, 
	"vkk" BINARY_DOUBLE, 
	"vk" BINARY_DOUBLE, 
	"kos" BINARY_DOUBLE, 
	"ikk" BINARY_DOUBLE, 
	"lkkkk" BINARY_DOUBLE, 
	"pkkkk" BINARY_DOUBLE, 
	"akm" BINARY_DOUBLE, 
	"pkm" BINARY_DOUBLE, 
	"roa" BINARY_DOUBLE, 
	"roe" BINARY_DOUBLE, 
	"ds_kaibevarad" BINARY_DOUBLE, 
	"ds_raha" BINARY_DOUBLE, 
	"ds_lyhiajalised_nouded" BINARY_DOUBLE, 
	"ds_lyhiajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_varud" BINARY_DOUBLE, 
	"ds_pohivarad" BINARY_DOUBLE, 
	"ds_pikaajalised_nouded" BINARY_DOUBLE, 
	"ds_pikaajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"ds_materiaalne_pohivara" BINARY_DOUBLE, 
	"ds_immateriaalne_pohivara" BINARY_DOUBLE, 
	"ds_varad_kokku" BINARY_DOUBLE, 
	"ds_lyhiajalised_kohustused" BINARY_DOUBLE, 
	"ds_lyhiajalised_volad" BINARY_DOUBLE, 
	"ds_lyhiajalised_laenud" BINARY_DOUBLE, 
	"ds_pikaajalised_kohustused" BINARY_DOUBLE, 
	"ds_pikaajalised_volad" BINARY_DOUBLE, 
	"ds_pikaajalised_laenud" BINARY_DOUBLE, 
	"ds_kohustused_kokku" BINARY_DOUBLE, 
	"ds_omakapital" BINARY_DOUBLE, 
	"ds_kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"ds_myygitulu" BINARY_DOUBLE, 
	"ds_muud_aritulud" BINARY_DOUBLE, 
	"ds_muud_arikulud" BINARY_DOUBLE, 
	"ds_toojoukulud" BINARY_DOUBLE, 
	"ds_arikasum" BINARY_DOUBLE, 
	"ds_intressikulud" BINARY_DOUBLE, 
	"ds_aruandeaasta_kasum" BINARY_DOUBLE, 
	"ettevotete_arv_sektoris" NUMBER(*,0), 
	"skoor_1_likviidsus" BINARY_DOUBLE, 
	"skoor_2_efektiivsus" BINARY_DOUBLE, 
	"skoor_3_struktuur" BINARY_DOUBLE, 
	"skoor_4_tasuvus" BINARY_DOUBLE, 
	"y_skoor_1_likviidsus" BINARY_DOUBLE, 
	"y_skoor_2_efektiivsus" BINARY_DOUBLE, 
	"y_skoor_3_struktuur" BINARY_DOUBLE, 
	"y_skoor_4_tasuvus" BINARY_DOUBLE, 
	"skp_jooksevhindades" BINARY_DOUBLE, 
	"skp_nominaalkasv" BINARY_DOUBLE, 
	"skp_pysivhindades" BINARY_DOUBLE, 
	"skp_reaalkasv" BINARY_DOUBLE, 
	"tarbijahinnaindeks" BINARY_DOUBLE, 
	"keskmine_kuupalk" BINARY_DOUBLE, 
	"palgakasv" BINARY_DOUBLE, 
	"tooviljakuse_kasv" BINARY_DOUBLE, 
	"sektor_likviidsus_protsentiil" BINARY_DOUBLE, 
	"sektor_efektiivsus_protsentiil" BINARY_DOUBLE, 
	"sektor_struktuur_protsentiil" BINARY_DOUBLE, 
	"sektor_tasuvus_protsentiil" BINARY_DOUBLE, 
	"klaster_likviidsus_protsentiil" BINARY_DOUBLE, 
	"klaster_efektiivsus_protsentii" BINARY_DOUBLE, 
	"klaster_struktuur_protsentiil" BINARY_DOUBLE, 
	"klaster_tasuvus_protsentiil" BINARY_DOUBLE, 
	"kov_likviidsus_protsentiil" BINARY_DOUBLE, 
	"kov_efektiivsus_protsentiil" BINARY_DOUBLE, 
	"kov_struktuur_protsentiil" BINARY_DOUBLE, 
	"kov_tasuvus_protsentiil" BINARY_DOUBLE, 
	"maakond_likviidsus_protsentiil" BINARY_DOUBLE, 
	"maakond_efektiivsus_protsentii" BINARY_DOUBLE, 
	"maakond_struktuur_protsentiil" BINARY_DOUBLE, 
	"maakond_tasuvus_protsentiil" BINARY_DOUBLE, 
	"maakond_x_klaster_likviidsus_p" BINARY_DOUBLE, 
	"maakond_x_klaster_efektiivsus_" BINARY_DOUBLE, 
	"maakond_x_klaster_struktuur_pr" BINARY_DOUBLE, 
	"maakond_x_klaster_tasuvus_prot" BINARY_DOUBLE, 
	"suurusklass_likviidsus_protsen" BINARY_DOUBLE, 
	"suurusklass_efektiivsus_protse" BINARY_DOUBLE, 
	"suurusklass_struktuur_protsent" BINARY_DOUBLE, 
	"suurusklass_tasuvus_protsentii" BINARY_DOUBLE, 
	"sektor_likviidsus_n" NUMBER(*,0), 
	"sektor_efektiivsus_n" NUMBER(*,0), 
	"sektor_struktuur_n" NUMBER(*,0), 
	"sektor_tasuvus_n" NUMBER(*,0), 
	"klaster_likviidsus_n" NUMBER(*,0), 
	"klaster_efektiivsus_n" NUMBER(*,0), 
	"klaster_struktuur_n" NUMBER(*,0), 
	"klaster_tasuvus_n" NUMBER(*,0), 
	"kov_likviidsus_n" NUMBER(*,0), 
	"kov_efektiivsus_n" NUMBER(*,0), 
	"kov_struktuur_n" NUMBER(*,0), 
	"kov_tasuvus_n" NUMBER(*,0), 
	"maakond_likviidsus_n" NUMBER(*,0), 
	"maakond_efektiivsus_n" NUMBER(*,0), 
	"maakond_struktuur_n" NUMBER(*,0), 
	"maakond_tasuvus_n" NUMBER(*,0), 
	"maakond_x_klaster_likviidsus_n" NUMBER(*,0), 
	"maakond_x_klaster_efektiivsusn" NUMBER(*,0), 
	"maakond_x_klaster_struktuur_n" NUMBER(*,0), 
	"maakond_x_klaster_tasuvus_n" NUMBER(*,0), 
	"suurusklass_likviidsus_n" NUMBER(*,0), 
	"suurusklass_efektiivsus_n" NUMBER(*,0), 
	"suurusklass_struktuur_n" NUMBER(*,0), 
	"suurusklass_tasuvus_n" NUMBER(*,0), 
	"maa_protsent" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."KUISED" 
   (	"kood" VARCHAR2(255 BYTE), 
	"emtak08" BINARY_DOUBLE, 
	"emtak_estat" VARCHAR2(255 BYTE), 
	"maa" BINARY_DOUBLE, 
	"vald" BINARY_DOUBLE, 
	"tarv_h" BINARY_DOUBLE, 
	"oig_grupp" VARCHAR2(255 BYTE), 
	"sektor_nr" NUMBER(*,0), 
	"sektor" VARCHAR2(255 BYTE), 
	"kmd_m_min12" BINARY_DOUBLE, 
	"kmd_m_min11" BINARY_DOUBLE, 
	"kmd_m_min10" BINARY_DOUBLE, 
	"kmd_m_min9" BINARY_DOUBLE, 
	"kmd_m_min8" BINARY_DOUBLE, 
	"kmd_m_min7" BINARY_DOUBLE, 
	"kmd_m_min6" BINARY_DOUBLE, 
	"kmd_m_min5" BINARY_DOUBLE, 
	"kmd_m_min4" BINARY_DOUBLE, 
	"kmd_m_min3" BINARY_DOUBLE, 
	"kmd_m_min2" BINARY_DOUBLE, 
	"kmd_m_min1" BINARY_DOUBLE, 
	"tsd_m_min12" BINARY_DOUBLE, 
	"tsd_m_min11" BINARY_DOUBLE, 
	"tsd_m_min10" BINARY_DOUBLE, 
	"tsd_m_min9" BINARY_DOUBLE, 
	"tsd_m_min8" BINARY_DOUBLE, 
	"tsd_m_min7" BINARY_DOUBLE, 
	"tsd_m_min6" BINARY_DOUBLE, 
	"tsd_m_min5" BINARY_DOUBLE, 
	"tsd_m_min4" BINARY_DOUBLE, 
	"tsd_m_min3" BINARY_DOUBLE, 
	"tsd_m_min2" BINARY_DOUBLE, 
	"tsd_m_min1" BINARY_DOUBLE, 
	"tor_m_min12" BINARY_DOUBLE, 
	"tor_m_min11" BINARY_DOUBLE, 
	"tor_m_min10" BINARY_DOUBLE, 
	"tor_m_min9" BINARY_DOUBLE, 
	"tor_m_min8" BINARY_DOUBLE, 
	"tor_m_min7" BINARY_DOUBLE, 
	"tor_m_min6" BINARY_DOUBLE, 
	"tor_m_min5" BINARY_DOUBLE, 
	"tor_m_min4" BINARY_DOUBLE, 
	"tor_m_min3" BINARY_DOUBLE, 
	"tor_m_min2" BINARY_DOUBLE, 
	"tor_m_min1" BINARY_DOUBLE, 
	"kmd_tsd_min1" BINARY_DOUBLE, 
	"kmd_tsd_min2" BINARY_DOUBLE, 
	"kmd_tsd_suht" BINARY_DOUBLE, 
	"suurusgrupp" VARCHAR2(255 BYTE), 
	"protsentiil_sektor" BINARY_DOUBLE, 
	"sektor_n" NUMBER(*,0), 
	"protsentiil_vald" BINARY_DOUBLE, 
	"vald_n" NUMBER(*,0), 
	"protsentiil_suurusgrupp" BINARY_DOUBLE, 
	"suurusgrupp_n" NUMBER(*,0), 
	"valjavottekuu" VARCHAR2(255 BYTE), 
	"klaster" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."NORM_AASTA_KESK_UUS" 
   (	"klaster" VARCHAR2(255 BYTE), 
	"aasta" BINARY_DOUBLE, 
	"kaibevarad" BINARY_DOUBLE, 
	"raha" BINARY_DOUBLE, 
	"lyhiajalised_nouded" BINARY_DOUBLE, 
	"lyhiajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"varud" BINARY_DOUBLE, 
	"pohivarad" BINARY_DOUBLE, 
	"pikaajalised_nouded" BINARY_DOUBLE, 
	"pikaajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"materiaalne_pohivara" BINARY_DOUBLE, 
	"immateriaalne_pohivara" BINARY_DOUBLE, 
	"varad_kokku" BINARY_DOUBLE, 
	"lyhiajalised_kohustused" BINARY_DOUBLE, 
	"lyhiajalised_volad" BINARY_DOUBLE, 
	"lyhiajalised_laenud" BINARY_DOUBLE, 
	"pikaajalised_kohustused" BINARY_DOUBLE, 
	"pikaajalised_volad" BINARY_DOUBLE, 
	"pikaajalised_laenud" BINARY_DOUBLE, 
	"kohustused_kokku" BINARY_DOUBLE, 
	"omakapital" BINARY_DOUBLE, 
	"kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"myygitulu" BINARY_DOUBLE, 
	"muud_aritulud" BINARY_DOUBLE, 
	"muud_arikulud" BINARY_DOUBLE, 
	"toojoukulud" BINARY_DOUBLE, 
	"arikasum" BINARY_DOUBLE, 
	"intressikulud" BINARY_DOUBLE, 
	"aruandeaasta_kasum" BINARY_DOUBLE, 
	"ds_kaibevarad" BINARY_DOUBLE, 
	"ds_raha" BINARY_DOUBLE, 
	"ds_lyhiajalised_nouded" BINARY_DOUBLE, 
	"ds_lyhiajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_varud" BINARY_DOUBLE, 
	"ds_pohivarad" BINARY_DOUBLE, 
	"ds_pikaajalised_nouded" BINARY_DOUBLE, 
	"ds_pikaajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"ds_materiaalne_pohivara" BINARY_DOUBLE, 
	"ds_immateriaalne_pohivara" BINARY_DOUBLE, 
	"ds_varad_kokku" BINARY_DOUBLE, 
	"ds_lyhiajalised_kohustused" BINARY_DOUBLE, 
	"ds_lyhiajalised_volad" BINARY_DOUBLE, 
	"ds_lyhiajalised_laenud" BINARY_DOUBLE, 
	"ds_pikaajalised_kohustused" BINARY_DOUBLE, 
	"ds_pikaajalised_volad" BINARY_DOUBLE, 
	"ds_pikaajalised_laenud" BINARY_DOUBLE, 
	"ds_kohustused_kokku" BINARY_DOUBLE, 
	"ds_omakapital" BINARY_DOUBLE, 
	"ds_kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"ds_myygitulu" BINARY_DOUBLE, 
	"ds_muud_aritulud" BINARY_DOUBLE, 
	"ds_muud_arikulud" BINARY_DOUBLE, 
	"ds_toojoukulud" BINARY_DOUBLE, 
	"ds_arikasum" BINARY_DOUBLE, 
	"ds_intressikulud" BINARY_DOUBLE, 
	"ds_aruandeaasta_kasum" BINARY_DOUBLE, 
	"skp_jooksevhindades" BINARY_DOUBLE, 
	"skp_nominaalkasv" BINARY_DOUBLE, 
	"skp_pysivhindades" BINARY_DOUBLE, 
	"skp_reaalkasv" BINARY_DOUBLE, 
	"tarbijahinnaindeks" BINARY_DOUBLE, 
	"keskmine_kuupalk" BINARY_DOUBLE, 
	"palgakasv" BINARY_DOUBLE, 
	"tooviljakuse_kasv" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."NORM_AASTA_KESK_VANA" 
   (	"klaster" VARCHAR2(255 BYTE), 
	"aasta" BINARY_DOUBLE, 
	"kaibevarad" BINARY_DOUBLE, 
	"raha" BINARY_DOUBLE, 
	"lyhiajalised_nouded" BINARY_DOUBLE, 
	"lyhiajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"varud" BINARY_DOUBLE, 
	"pohivarad" BINARY_DOUBLE, 
	"pikaajalised_nouded" BINARY_DOUBLE, 
	"pikaajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"materiaalne_pohivara" BINARY_DOUBLE, 
	"immateriaalne_pohivara" BINARY_DOUBLE, 
	"varad_kokku" BINARY_DOUBLE, 
	"lyhiajalised_kohustused" BINARY_DOUBLE, 
	"lyhiajalised_volad" BINARY_DOUBLE, 
	"lyhiajalised_laenud" BINARY_DOUBLE, 
	"pikaajalised_kohustused" BINARY_DOUBLE, 
	"pikaajalised_volad" BINARY_DOUBLE, 
	"pikaajalised_laenud" BINARY_DOUBLE, 
	"kohustused_kokku" BINARY_DOUBLE, 
	"omakapital" BINARY_DOUBLE, 
	"kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"myygitulu" BINARY_DOUBLE, 
	"muud_aritulud" BINARY_DOUBLE, 
	"muud_arikulud" BINARY_DOUBLE, 
	"toojoukulud" BINARY_DOUBLE, 
	"arikasum" BINARY_DOUBLE, 
	"intressikulud" BINARY_DOUBLE, 
	"aruandeaasta_kasum" BINARY_DOUBLE, 
	"ds_kaibevarad" BINARY_DOUBLE, 
	"ds_raha" BINARY_DOUBLE, 
	"ds_lyhiajalised_nouded" BINARY_DOUBLE, 
	"ds_lyhiajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_varud" BINARY_DOUBLE, 
	"ds_pohivarad" BINARY_DOUBLE, 
	"ds_pikaajalised_nouded" BINARY_DOUBLE, 
	"ds_pikaajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"ds_materiaalne_pohivara" BINARY_DOUBLE, 
	"ds_immateriaalne_pohivara" BINARY_DOUBLE, 
	"ds_varad_kokku" BINARY_DOUBLE, 
	"ds_lyhiajalised_kohustused" BINARY_DOUBLE, 
	"ds_lyhiajalised_volad" BINARY_DOUBLE, 
	"ds_lyhiajalised_laenud" BINARY_DOUBLE, 
	"ds_pikaajalised_kohustused" BINARY_DOUBLE, 
	"ds_pikaajalised_volad" BINARY_DOUBLE, 
	"ds_pikaajalised_laenud" BINARY_DOUBLE, 
	"ds_kohustused_kokku" BINARY_DOUBLE, 
	"ds_omakapital" BINARY_DOUBLE, 
	"ds_kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"ds_myygitulu" BINARY_DOUBLE, 
	"ds_muud_aritulud" BINARY_DOUBLE, 
	"ds_muud_arikulud" BINARY_DOUBLE, 
	"ds_toojoukulud" BINARY_DOUBLE, 
	"ds_arikasum" BINARY_DOUBLE, 
	"ds_intressikulud" BINARY_DOUBLE, 
	"ds_aruandeaasta_kasum" BINARY_DOUBLE, 
	"skp_jooksevhindades" BINARY_DOUBLE, 
	"skp_nominaalkasv" BINARY_DOUBLE, 
	"skp_pysivhindades" BINARY_DOUBLE, 
	"skp_reaalkasv" BINARY_DOUBLE, 
	"tarbijahinnaindeks" BINARY_DOUBLE, 
	"keskmine_kuupalk" BINARY_DOUBLE, 
	"palgakasv" BINARY_DOUBLE, 
	"tooviljakuse_kasv" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."NORM_AASTA_SDS_UUS" 
   (	"klaster" VARCHAR2(255 BYTE), 
	"aasta" BINARY_DOUBLE, 
	"kaibevarad" BINARY_DOUBLE, 
	"raha" BINARY_DOUBLE, 
	"lyhiajalised_nouded" BINARY_DOUBLE, 
	"lyhiajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"varud" BINARY_DOUBLE, 
	"pohivarad" BINARY_DOUBLE, 
	"pikaajalised_nouded" BINARY_DOUBLE, 
	"pikaajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"materiaalne_pohivara" BINARY_DOUBLE, 
	"immateriaalne_pohivara" BINARY_DOUBLE, 
	"varad_kokku" BINARY_DOUBLE, 
	"lyhiajalised_kohustused" BINARY_DOUBLE, 
	"lyhiajalised_volad" BINARY_DOUBLE, 
	"lyhiajalised_laenud" BINARY_DOUBLE, 
	"pikaajalised_kohustused" BINARY_DOUBLE, 
	"pikaajalised_volad" BINARY_DOUBLE, 
	"pikaajalised_laenud" BINARY_DOUBLE, 
	"kohustused_kokku" BINARY_DOUBLE, 
	"omakapital" BINARY_DOUBLE, 
	"kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"myygitulu" BINARY_DOUBLE, 
	"muud_aritulud" BINARY_DOUBLE, 
	"muud_arikulud" BINARY_DOUBLE, 
	"toojoukulud" BINARY_DOUBLE, 
	"arikasum" BINARY_DOUBLE, 
	"intressikulud" BINARY_DOUBLE, 
	"aruandeaasta_kasum" BINARY_DOUBLE, 
	"ds_kaibevarad" BINARY_DOUBLE, 
	"ds_raha" BINARY_DOUBLE, 
	"ds_lyhiajalised_nouded" BINARY_DOUBLE, 
	"ds_lyhiajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_varud" BINARY_DOUBLE, 
	"ds_pohivarad" BINARY_DOUBLE, 
	"ds_pikaajalised_nouded" BINARY_DOUBLE, 
	"ds_pikaajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"ds_materiaalne_pohivara" BINARY_DOUBLE, 
	"ds_immateriaalne_pohivara" BINARY_DOUBLE, 
	"ds_varad_kokku" BINARY_DOUBLE, 
	"ds_lyhiajalised_kohustused" BINARY_DOUBLE, 
	"ds_lyhiajalised_volad" BINARY_DOUBLE, 
	"ds_lyhiajalised_laenud" BINARY_DOUBLE, 
	"ds_pikaajalised_kohustused" BINARY_DOUBLE, 
	"ds_pikaajalised_volad" BINARY_DOUBLE, 
	"ds_pikaajalised_laenud" BINARY_DOUBLE, 
	"ds_kohustused_kokku" BINARY_DOUBLE, 
	"ds_omakapital" BINARY_DOUBLE, 
	"ds_kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"ds_myygitulu" BINARY_DOUBLE, 
	"ds_muud_aritulud" BINARY_DOUBLE, 
	"ds_muud_arikulud" BINARY_DOUBLE, 
	"ds_toojoukulud" BINARY_DOUBLE, 
	"ds_arikasum" BINARY_DOUBLE, 
	"ds_intressikulud" BINARY_DOUBLE, 
	"ds_aruandeaasta_kasum" BINARY_DOUBLE, 
	"skp_jooksevhindades" BINARY_DOUBLE, 
	"skp_nominaalkasv" BINARY_DOUBLE, 
	"skp_pysivhindades" BINARY_DOUBLE, 
	"skp_reaalkasv" BINARY_DOUBLE, 
	"tarbijahinnaindeks" BINARY_DOUBLE, 
	"keskmine_kuupalk" BINARY_DOUBLE, 
	"palgakasv" BINARY_DOUBLE, 
	"tooviljakuse_kasv" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."NORM_AASTA_SDS_VANA" 
   (	"klaster" VARCHAR2(255 BYTE), 
	"aasta" BINARY_DOUBLE, 
	"kaibevarad" BINARY_DOUBLE, 
	"raha" BINARY_DOUBLE, 
	"lyhiajalised_nouded" BINARY_DOUBLE, 
	"lyhiajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"varud" BINARY_DOUBLE, 
	"pohivarad" BINARY_DOUBLE, 
	"pikaajalised_nouded" BINARY_DOUBLE, 
	"pikaajalised_finantsinvesteeri" BINARY_DOUBLE, 
	"kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"materiaalne_pohivara" BINARY_DOUBLE, 
	"immateriaalne_pohivara" BINARY_DOUBLE, 
	"varad_kokku" BINARY_DOUBLE, 
	"lyhiajalised_kohustused" BINARY_DOUBLE, 
	"lyhiajalised_volad" BINARY_DOUBLE, 
	"lyhiajalised_laenud" BINARY_DOUBLE, 
	"pikaajalised_kohustused" BINARY_DOUBLE, 
	"pikaajalised_volad" BINARY_DOUBLE, 
	"pikaajalised_laenud" BINARY_DOUBLE, 
	"kohustused_kokku" BINARY_DOUBLE, 
	"omakapital" BINARY_DOUBLE, 
	"kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"myygitulu" BINARY_DOUBLE, 
	"muud_aritulud" BINARY_DOUBLE, 
	"muud_arikulud" BINARY_DOUBLE, 
	"toojoukulud" BINARY_DOUBLE, 
	"arikasum" BINARY_DOUBLE, 
	"intressikulud" BINARY_DOUBLE, 
	"aruandeaasta_kasum" BINARY_DOUBLE, 
	"ds_kaibevarad" BINARY_DOUBLE, 
	"ds_raha" BINARY_DOUBLE, 
	"ds_lyhiajalised_nouded" BINARY_DOUBLE, 
	"ds_lyhiajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_varud" BINARY_DOUBLE, 
	"ds_pohivarad" BINARY_DOUBLE, 
	"ds_pikaajalised_nouded" BINARY_DOUBLE, 
	"ds_pikaajalised_finantsinveste" BINARY_DOUBLE, 
	"ds_kinnisvarainvesteeringud" BINARY_DOUBLE, 
	"ds_materiaalne_pohivara" BINARY_DOUBLE, 
	"ds_immateriaalne_pohivara" BINARY_DOUBLE, 
	"ds_varad_kokku" BINARY_DOUBLE, 
	"ds_lyhiajalised_kohustused" BINARY_DOUBLE, 
	"ds_lyhiajalised_volad" BINARY_DOUBLE, 
	"ds_lyhiajalised_laenud" BINARY_DOUBLE, 
	"ds_pikaajalised_kohustused" BINARY_DOUBLE, 
	"ds_pikaajalised_volad" BINARY_DOUBLE, 
	"ds_pikaajalised_laenud" BINARY_DOUBLE, 
	"ds_kohustused_kokku" BINARY_DOUBLE, 
	"ds_omakapital" BINARY_DOUBLE, 
	"ds_kohustused_omakapital_kokku" BINARY_DOUBLE, 
	"ds_myygitulu" BINARY_DOUBLE, 
	"ds_muud_aritulud" BINARY_DOUBLE, 
	"ds_muud_arikulud" BINARY_DOUBLE, 
	"ds_toojoukulud" BINARY_DOUBLE, 
	"ds_arikasum" BINARY_DOUBLE, 
	"ds_intressikulud" BINARY_DOUBLE, 
	"ds_aruandeaasta_kasum" BINARY_DOUBLE, 
	"skp_jooksevhindades" BINARY_DOUBLE, 
	"skp_nominaalkasv" BINARY_DOUBLE, 
	"skp_pysivhindades" BINARY_DOUBLE, 
	"skp_reaalkasv" BINARY_DOUBLE, 
	"tarbijahinnaindeks" BINARY_DOUBLE, 
	"keskmine_kuupalk" BINARY_DOUBLE, 
	"palgakasv" BINARY_DOUBLE, 
	"tooviljakuse_kasv" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."NORM_KUU_KESK" 
   (	"klaster" VARCHAR2(255 BYTE), 
	"kmd_m_min12" BINARY_DOUBLE, 
	"kmd_m_min11" BINARY_DOUBLE, 
	"kmd_m_min10" BINARY_DOUBLE, 
	"kmd_m_min9" BINARY_DOUBLE, 
	"kmd_m_min8" BINARY_DOUBLE, 
	"kmd_m_min7" BINARY_DOUBLE, 
	"kmd_m_min6" BINARY_DOUBLE, 
	"kmd_m_min5" BINARY_DOUBLE, 
	"kmd_m_min4" BINARY_DOUBLE, 
	"kmd_m_min3" BINARY_DOUBLE, 
	"kmd_m_min2" BINARY_DOUBLE, 
	"kmd_m_min1" BINARY_DOUBLE, 
	"tsd_m_min12" BINARY_DOUBLE, 
	"tsd_m_min11" BINARY_DOUBLE, 
	"tsd_m_min10" BINARY_DOUBLE, 
	"tsd_m_min9" BINARY_DOUBLE, 
	"tsd_m_min8" BINARY_DOUBLE, 
	"tsd_m_min7" BINARY_DOUBLE, 
	"tsd_m_min6" BINARY_DOUBLE, 
	"tsd_m_min5" BINARY_DOUBLE, 
	"tsd_m_min4" BINARY_DOUBLE, 
	"tsd_m_min3" BINARY_DOUBLE, 
	"tsd_m_min2" BINARY_DOUBLE, 
	"tsd_m_min1" BINARY_DOUBLE, 
	"tor_m_min12" BINARY_DOUBLE, 
	"tor_m_min11" BINARY_DOUBLE, 
	"tor_m_min10" BINARY_DOUBLE, 
	"tor_m_min9" BINARY_DOUBLE, 
	"tor_m_min8" BINARY_DOUBLE, 
	"tor_m_min7" BINARY_DOUBLE, 
	"tor_m_min6" BINARY_DOUBLE, 
	"tor_m_min5" BINARY_DOUBLE, 
	"tor_m_min4" BINARY_DOUBLE, 
	"tor_m_min3" BINARY_DOUBLE, 
	"tor_m_min2" BINARY_DOUBLE, 
	"tor_m_min1" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "ELUJOULISUSEINDEKS"."NORM_KUU_SDS" 
   (	"klaster" VARCHAR2(255 BYTE), 
	"kmd_m_min12" BINARY_DOUBLE, 
	"kmd_m_min11" BINARY_DOUBLE, 
	"kmd_m_min10" BINARY_DOUBLE, 
	"kmd_m_min9" BINARY_DOUBLE, 
	"kmd_m_min8" BINARY_DOUBLE, 
	"kmd_m_min7" BINARY_DOUBLE, 
	"kmd_m_min6" BINARY_DOUBLE, 
	"kmd_m_min5" BINARY_DOUBLE, 
	"kmd_m_min4" BINARY_DOUBLE, 
	"kmd_m_min3" BINARY_DOUBLE, 
	"kmd_m_min2" BINARY_DOUBLE, 
	"kmd_m_min1" BINARY_DOUBLE, 
	"tsd_m_min12" BINARY_DOUBLE, 
	"tsd_m_min11" BINARY_DOUBLE, 
	"tsd_m_min10" BINARY_DOUBLE, 
	"tsd_m_min9" BINARY_DOUBLE, 
	"tsd_m_min8" BINARY_DOUBLE, 
	"tsd_m_min7" BINARY_DOUBLE, 
	"tsd_m_min6" BINARY_DOUBLE, 
	"tsd_m_min5" BINARY_DOUBLE, 
	"tsd_m_min4" BINARY_DOUBLE, 
	"tsd_m_min3" BINARY_DOUBLE, 
	"tsd_m_min2" BINARY_DOUBLE, 
	"tsd_m_min1" BINARY_DOUBLE, 
	"tor_m_min12" BINARY_DOUBLE, 
	"tor_m_min11" BINARY_DOUBLE, 
	"tor_m_min10" BINARY_DOUBLE, 
	"tor_m_min9" BINARY_DOUBLE, 
	"tor_m_min8" BINARY_DOUBLE, 
	"tor_m_min7" BINARY_DOUBLE, 
	"tor_m_min6" BINARY_DOUBLE, 
	"tor_m_min5" BINARY_DOUBLE, 
	"tor_m_min4" BINARY_DOUBLE, 
	"tor_m_min3" BINARY_DOUBLE, 
	"tor_m_min2" BINARY_DOUBLE, 
	"tor_m_min1" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

