SET check_function_bodies = false;
CREATE SCHEMA elujoulisuseindeks;
CREATE TABLE elujoulisuseindeks.aastased (
    jykood text,
    aasta double precision,
    emtak double precision,
    sektor_nr double precision,
    sektor_txt text,
    klaster text,
    tarv_h double precision,
    oig_vorm text,
    ettevotte_suurusklass double precision,
    asu_kood double precision,
    kov double precision,
    maakond double precision,
    kaibevarad double precision,
    raha double precision,
    lyhiajalised_nouded double precision,
    lyhiajalised_finantsinvesteeri double precision,
    varud double precision,
    pohivarad double precision,
    pikaajalised_nouded double precision,
    pikaajalised_finantsinvesteeri double precision,
    kinnisvarainvesteeringud double precision,
    materiaalne_pohivara double precision,
    immateriaalne_pohivara double precision,
    varad_kokku double precision,
    lyhiajalised_kohustused double precision,
    lyhiajalised_volad double precision,
    lyhiajalised_laenud double precision,
    pikaajalised_kohustused double precision,
    pikaajalised_volad double precision,
    pikaajalised_laenud double precision,
    kohustused_kokku double precision,
    omakapital double precision,
    kohustused_omakapital_kokku double precision,
    myygitulu double precision,
    muud_aritulud double precision,
    muud_arikulud double precision,
    toojoukulud double precision,
    arikasum double precision,
    intressikulud double precision,
    aruandeaasta_kasum double precision,
    lvkk double precision,
    mvk double precision,
    rk double precision,
    lllk double precision,
    llvk double precision,
    llok double precision,
    vakk double precision,
    lvkak double precision,
    vkk double precision,
    vk double precision,
    kos double precision,
    ikk double precision,
    lkkkk double precision,
    pkkkk double precision,
    akm double precision,
    pkm double precision,
    roa double precision,
    roe double precision,
    ds_kaibevarad double precision,
    ds_raha double precision,
    ds_lyhiajalised_nouded double precision,
    ds_lyhiajalised_finantsinveste double precision,
    ds_varud double precision,
    ds_pohivarad double precision,
    ds_pikaajalised_nouded double precision,
    ds_pikaajalised_finantsinveste double precision,
    ds_kinnisvarainvesteeringud double precision,
    ds_materiaalne_pohivara double precision,
    ds_immateriaalne_pohivara double precision,
    ds_varad_kokku double precision,
    ds_lyhiajalised_kohustused double precision,
    ds_lyhiajalised_volad double precision,
    ds_lyhiajalised_laenud double precision,
    ds_pikaajalised_kohustused double precision,
    ds_pikaajalised_volad double precision,
    ds_pikaajalised_laenud double precision,
    ds_kohustused_kokku double precision,
    ds_omakapital double precision,
    ds_kohustused_omakapital_kokku double precision,
    ds_myygitulu double precision,
    ds_muud_aritulud double precision,
    ds_muud_arikulud double precision,
    ds_toojoukulud double precision,
    ds_arikasum double precision,
    ds_intressikulud double precision,
    ds_aruandeaasta_kasum double precision,
    ettevotete_arv_sektoris integer,
    skoor_1_likviidsus double precision,
    skoor_2_efektiivsus double precision,
    skoor_3_struktuur double precision,
    skoor_4_tasuvus double precision,
    y_skoor_1_likviidsus double precision,
    y_skoor_2_efektiivsus double precision,
    y_skoor_3_struktuur double precision,
    y_skoor_4_tasuvus double precision,
    skp_jooksevhindades double precision,
    skp_nominaalkasv double precision,
    skp_pysivhindades double precision,
    skp_reaalkasv double precision,
    tarbijahinnaindeks double precision,
    keskmine_kuupalk double precision,
    palgakasv double precision,
    tooviljakuse_kasv double precision,
    sektor_likviidsus_protsentiil double precision,
    sektor_efektiivsus_protsentiil double precision,
    sektor_struktuur_protsentiil double precision,
    sektor_tasuvus_protsentiil double precision,
    klaster_likviidsus_protsentiil double precision,
    klaster_efektiivsus_protsentii double precision,
    klaster_struktuur_protsentiil double precision,
    klaster_tasuvus_protsentiil double precision,
    kov_likviidsus_protsentiil double precision,
    kov_efektiivsus_protsentiil double precision,
    kov_struktuur_protsentiil double precision,
    kov_tasuvus_protsentiil double precision,
    maakond_likviidsus_protsentiil double precision,
    maakond_efektiivsus_protsentii double precision,
    maakond_struktuur_protsentiil double precision,
    maakond_tasuvus_protsentiil double precision,
    maakond_x_klaster_likviidsus_p double precision,
    maakond_x_klaster_efektiivsus_ double precision,
    maakond_x_klaster_struktuur_pr double precision,
    maakond_x_klaster_tasuvus_prot double precision,
    suurusklass_likviidsus_protsen double precision,
    suurusklass_efektiivsus_protse double precision,
    suurusklass_struktuur_protsent double precision,
    suurusklass_tasuvus_protsentii double precision,
    sektor_likviidsus_n integer,
    sektor_efektiivsus_n integer,
    sektor_struktuur_n integer,
    sektor_tasuvus_n integer,
    klaster_likviidsus_n integer,
    klaster_efektiivsus_n integer,
    klaster_struktuur_n integer,
    klaster_tasuvus_n integer,
    kov_likviidsus_n integer,
    kov_efektiivsus_n integer,
    kov_struktuur_n integer,
    kov_tasuvus_n integer,
    maakond_likviidsus_n integer,
    maakond_efektiivsus_n integer,
    maakond_struktuur_n integer,
    maakond_tasuvus_n integer,
    maakond_x_klaster_likviidsus_n integer,
    maakond_x_klaster_efektiivsusn integer,
    maakond_x_klaster_struktuur_n integer,
    maakond_x_klaster_tasuvus_n integer,
    suurusklass_likviidsus_n integer,
    suurusklass_efektiivsus_n integer,
    suurusklass_struktuur_n integer,
    suurusklass_tasuvus_n integer,
    maa_protsent double precision
);
CREATE TABLE elujoulisuseindeks.kuised (
    kood text,
    emtak08 double precision,
    emtak_estat text,
    maa double precision,
    vald double precision,
    tarv_h double precision,
    oig_grupp text,
    sektor_nr integer,
    sektor text,
    kmd_m_min12 double precision,
    kmd_m_min11 double precision,
    kmd_m_min10 double precision,
    kmd_m_min9 double precision,
    kmd_m_min8 double precision,
    kmd_m_min7 double precision,
    kmd_m_min6 double precision,
    kmd_m_min5 double precision,
    kmd_m_min4 double precision,
    kmd_m_min3 double precision,
    kmd_m_min2 double precision,
    kmd_m_min1 double precision,
    tsd_m_min12 double precision,
    tsd_m_min11 double precision,
    tsd_m_min10 double precision,
    tsd_m_min9 double precision,
    tsd_m_min8 double precision,
    tsd_m_min7 double precision,
    tsd_m_min6 double precision,
    tsd_m_min5 double precision,
    tsd_m_min4 double precision,
    tsd_m_min3 double precision,
    tsd_m_min2 double precision,
    tsd_m_min1 double precision,
    tor_m_min12 double precision,
    tor_m_min11 double precision,
    tor_m_min10 double precision,
    tor_m_min9 double precision,
    tor_m_min8 double precision,
    tor_m_min7 double precision,
    tor_m_min6 double precision,
    tor_m_min5 double precision,
    tor_m_min4 double precision,
    tor_m_min3 double precision,
    tor_m_min2 double precision,
    tor_m_min1 double precision,
    kmd_tsd_min1 double precision,
    kmd_tsd_min2 double precision,
    kmd_tsd_suht double precision,
    suurusgrupp text,
    protsentiil_sektor double precision,
    sektor_n integer,
    protsentiil_vald double precision,
    vald_n integer,
    protsentiil_suurusgrupp double precision,
    suurusgrupp_n integer,
    valjavottekuu text,
    klaster text
);
CREATE TABLE elujoulisuseindeks.norm_aasta_kesk_uus (
    klaster text,
    aasta double precision,
    kaibevarad double precision,
    raha double precision,
    lyhiajalised_nouded double precision,
    lyhiajalised_finantsinvesteeri double precision,
    varud double precision,
    pohivarad double precision,
    pikaajalised_nouded double precision,
    pikaajalised_finantsinvesteeri double precision,
    kinnisvarainvesteeringud double precision,
    materiaalne_pohivara double precision,
    immateriaalne_pohivara double precision,
    varad_kokku double precision,
    lyhiajalised_kohustused double precision,
    lyhiajalised_volad double precision,
    lyhiajalised_laenud double precision,
    pikaajalised_kohustused double precision,
    pikaajalised_volad double precision,
    pikaajalised_laenud double precision,
    kohustused_kokku double precision,
    omakapital double precision,
    kohustused_omakapital_kokku double precision,
    myygitulu double precision,
    muud_aritulud double precision,
    muud_arikulud double precision,
    toojoukulud double precision,
    arikasum double precision,
    intressikulud double precision,
    aruandeaasta_kasum double precision,
    ds_kaibevarad double precision,
    ds_raha double precision,
    ds_lyhiajalised_nouded double precision,
    ds_lyhiajalised_finantsinveste double precision,
    ds_varud double precision,
    ds_pohivarad double precision,
    ds_pikaajalised_nouded double precision,
    ds_pikaajalised_finantsinveste double precision,
    ds_kinnisvarainvesteeringud double precision,
    ds_materiaalne_pohivara double precision,
    ds_immateriaalne_pohivara double precision,
    ds_varad_kokku double precision,
    ds_lyhiajalised_kohustused double precision,
    ds_lyhiajalised_volad double precision,
    ds_lyhiajalised_laenud double precision,
    ds_pikaajalised_kohustused double precision,
    ds_pikaajalised_volad double precision,
    ds_pikaajalised_laenud double precision,
    ds_kohustused_kokku double precision,
    ds_omakapital double precision,
    ds_kohustused_omakapital_kokku double precision,
    ds_myygitulu double precision,
    ds_muud_aritulud double precision,
    ds_muud_arikulud double precision,
    ds_toojoukulud double precision,
    ds_arikasum double precision,
    ds_intressikulud double precision,
    ds_aruandeaasta_kasum double precision,
    skp_jooksevhindades double precision,
    skp_nominaalkasv double precision,
    skp_pysivhindades double precision,
    skp_reaalkasv double precision,
    tarbijahinnaindeks double precision,
    keskmine_kuupalk double precision,
    palgakasv double precision,
    tooviljakuse_kasv double precision
);
CREATE TABLE elujoulisuseindeks.norm_aasta_kesk_vana (
    klaster text,
    aasta double precision,
    kaibevarad double precision,
    raha double precision,
    lyhiajalised_nouded double precision,
    lyhiajalised_finantsinvesteeri double precision,
    varud double precision,
    pohivarad double precision,
    pikaajalised_nouded double precision,
    pikaajalised_finantsinvesteeri double precision,
    kinnisvarainvesteeringud double precision,
    materiaalne_pohivara double precision,
    immateriaalne_pohivara double precision,
    varad_kokku double precision,
    lyhiajalised_kohustused double precision,
    lyhiajalised_volad double precision,
    lyhiajalised_laenud double precision,
    pikaajalised_kohustused double precision,
    pikaajalised_volad double precision,
    pikaajalised_laenud double precision,
    kohustused_kokku double precision,
    omakapital double precision,
    kohustused_omakapital_kokku double precision,
    myygitulu double precision,
    muud_aritulud double precision,
    muud_arikulud double precision,
    toojoukulud double precision,
    arikasum double precision,
    intressikulud double precision,
    aruandeaasta_kasum double precision,
    ds_kaibevarad double precision,
    ds_raha double precision,
    ds_lyhiajalised_nouded double precision,
    ds_lyhiajalised_finantsinveste double precision,
    ds_varud double precision,
    ds_pohivarad double precision,
    ds_pikaajalised_nouded double precision,
    ds_pikaajalised_finantsinveste double precision,
    ds_kinnisvarainvesteeringud double precision,
    ds_materiaalne_pohivara double precision,
    ds_immateriaalne_pohivara double precision,
    ds_varad_kokku double precision,
    ds_lyhiajalised_kohustused double precision,
    ds_lyhiajalised_volad double precision,
    ds_lyhiajalised_laenud double precision,
    ds_pikaajalised_kohustused double precision,
    ds_pikaajalised_volad double precision,
    ds_pikaajalised_laenud double precision,
    ds_kohustused_kokku double precision,
    ds_omakapital double precision,
    ds_kohustused_omakapital_kokku double precision,
    ds_myygitulu double precision,
    ds_muud_aritulud double precision,
    ds_muud_arikulud double precision,
    ds_toojoukulud double precision,
    ds_arikasum double precision,
    ds_intressikulud double precision,
    ds_aruandeaasta_kasum double precision,
    skp_jooksevhindades double precision,
    skp_nominaalkasv double precision,
    skp_pysivhindades double precision,
    skp_reaalkasv double precision,
    tarbijahinnaindeks double precision,
    keskmine_kuupalk double precision,
    palgakasv double precision,
    tooviljakuse_kasv double precision
);
CREATE TABLE elujoulisuseindeks.norm_aasta_sds_vana (
    klaster text,
    aasta double precision,
    kaibevarad double precision,
    raha double precision,
    lyhiajalised_nouded double precision,
    lyhiajalised_finantsinvesteeri double precision,
    varud double precision,
    pohivarad double precision,
    pikaajalised_nouded double precision,
    pikaajalised_finantsinvesteeri double precision,
    kinnisvarainvesteeringud double precision,
    materiaalne_pohivara double precision,
    immateriaalne_pohivara double precision,
    varad_kokku double precision,
    lyhiajalised_kohustused double precision,
    lyhiajalised_volad double precision,
    lyhiajalised_laenud double precision,
    pikaajalised_kohustused double precision,
    pikaajalised_volad double precision,
    pikaajalised_laenud double precision,
    kohustused_kokku double precision,
    omakapital double precision,
    kohustused_omakapital_kokku double precision,
    myygitulu double precision,
    muud_aritulud double precision,
    muud_arikulud double precision,
    toojoukulud double precision,
    arikasum double precision,
    intressikulud double precision,
    aruandeaasta_kasum double precision,
    ds_kaibevarad double precision,
    ds_raha double precision,
    ds_lyhiajalised_nouded double precision,
    ds_lyhiajalised_finantsinveste double precision,
    ds_varud double precision,
    ds_pohivarad double precision,
    ds_pikaajalised_nouded double precision,
    ds_pikaajalised_finantsinveste double precision,
    ds_kinnisvarainvesteeringud double precision,
    ds_materiaalne_pohivara double precision,
    ds_immateriaalne_pohivara double precision,
    ds_varad_kokku double precision,
    ds_lyhiajalised_kohustused double precision,
    ds_lyhiajalised_volad double precision,
    ds_lyhiajalised_laenud double precision,
    ds_pikaajalised_kohustused double precision,
    ds_pikaajalised_volad double precision,
    ds_pikaajalised_laenud double precision,
    ds_kohustused_kokku double precision,
    ds_omakapital double precision,
    ds_kohustused_omakapital_kokku double precision,
    ds_myygitulu double precision,
    ds_muud_aritulud double precision,
    ds_muud_arikulud double precision,
    ds_toojoukulud double precision,
    ds_arikasum double precision,
    ds_intressikulud double precision,
    ds_aruandeaasta_kasum double precision,
    skp_jooksevhindades double precision,
    skp_nominaalkasv double precision,
    skp_pysivhindades double precision,
    skp_reaalkasv double precision,
    tarbijahinnaindeks double precision,
    keskmine_kuupalk double precision,
    palgakasv double precision,
    tooviljakuse_kasv double precision
);
CREATE TABLE elujoulisuseindeks.norm_kuu_kesk (
    klaster text,
    kmd_m_min12 double precision,
    kmd_m_min11 double precision,
    kmd_m_min10 double precision,
    kmd_m_min9 double precision,
    kmd_m_min8 double precision,
    kmd_m_min7 double precision,
    kmd_m_min6 double precision,
    kmd_m_min5 double precision,
    kmd_m_min4 double precision,
    kmd_m_min3 double precision,
    kmd_m_min2 double precision,
    kmd_m_min1 double precision,
    tsd_m_min12 double precision,
    tsd_m_min11 double precision,
    tsd_m_min10 double precision,
    tsd_m_min9 double precision,
    tsd_m_min8 double precision,
    tsd_m_min7 double precision,
    tsd_m_min6 double precision,
    tsd_m_min5 double precision,
    tsd_m_min4 double precision,
    tsd_m_min3 double precision,
    tsd_m_min2 double precision,
    tsd_m_min1 double precision,
    tor_m_min12 double precision,
    tor_m_min11 double precision,
    tor_m_min10 double precision,
    tor_m_min9 double precision,
    tor_m_min8 double precision,
    tor_m_min7 double precision,
    tor_m_min6 double precision,
    tor_m_min5 double precision,
    tor_m_min4 double precision,
    tor_m_min3 double precision,
    tor_m_min2 double precision,
    tor_m_min1 double precision
);
CREATE TABLE elujoulisuseindeks.norm_kuu_sds (
    klaster text,
    kmd_m_min12 double precision,
    kmd_m_min11 double precision,
    kmd_m_min10 double precision,
    kmd_m_min9 double precision,
    kmd_m_min8 double precision,
    kmd_m_min7 double precision,
    kmd_m_min6 double precision,
    kmd_m_min5 double precision,
    kmd_m_min4 double precision,
    kmd_m_min3 double precision,
    kmd_m_min2 double precision,
    kmd_m_min1 double precision,
    tsd_m_min12 double precision,
    tsd_m_min11 double precision,
    tsd_m_min10 double precision,
    tsd_m_min9 double precision,
    tsd_m_min8 double precision,
    tsd_m_min7 double precision,
    tsd_m_min6 double precision,
    tsd_m_min5 double precision,
    tsd_m_min4 double precision,
    tsd_m_min3 double precision,
    tsd_m_min2 double precision,
    tsd_m_min1 double precision,
    tor_m_min12 double precision,
    tor_m_min11 double precision,
    tor_m_min10 double precision,
    tor_m_min9 double precision,
    tor_m_min8 double precision,
    tor_m_min7 double precision,
    tor_m_min6 double precision,
    tor_m_min5 double precision,
    tor_m_min4 double precision,
    tor_m_min3 double precision,
    tor_m_min2 double precision,
    tor_m_min1 double precision
);
