import { ApiResponse, PredictionResponse } from "../domain/index";
import { Company as Year, MonthlyCluster } from "../infrastructure/models";

interface BuildResponseParams {
  prediction: PredictionResponse;
  monthly: MonthlyCluster | null;
  year: Year;
}

export function buildSuccess(params: BuildResponseParams): ApiResponse {
  const year = params.year;
  const monthly = params.monthly;
  const prediction = params.prediction;

  const response: ApiResponse = {
    Emp_n_Count: monthly?.vald_n ?? null,
    Emp_n_Sect: monthly?.sektor_n ?? null,
    Emp_n_Size: monthly?.suurusgrupp_n ?? null,
    EmppCount: monthly?.protsentiil_vald ?? null,
    EmppSect: monthly?.protsentiil_sektor ?? null,
    EmppSize: monthly?.protsentiil_suurusgrupp ?? null,
    hoiv: monthly?.tor_m_min1 ?? null,
    TJT: monthly?.kmd_tsd_min2 ?? null,
    AKM: year.akm,
    county: year.maakond,
    Eff_n_Count: year.maakond_efektiivsus_n,
    Eff_n_Sect: year.sektor_efektiivsus_n,
    Eff_n_Size: year.suurusklass_efektiivsus_n,
    EffpCount: year.maakond_efektiivsus_protsentii,
    EffpSect: year.sektor_efektiivsus_protsentiil,
    EffpSize: year.suurusklass_efektiivsus_protse,
    EMTAK: `${year.emtak}`,
    IKK: year.ikk,
    KOS: year.kos,
    kov: year.kov,
    Lev_n_Count: year.maakond_struktuur_n,
    Lev_n_Sect: year.sektor_struktuur_n,
    Lev_n_Size: year.suurusklass_struktuur_n,
    LevpCount: year.maakond_struktuur_protsentiil,
    LevpSect: year.sektor_struktuur_protsentiil,
    LevpSize: year.suurusklass_struktuur_protsent,
    Liq_n_Count: year.maakond_likviidsus_n,
    Liq_n_Sect: year.sektor_likviidsus_n,
    Liq_n_Size: year.suurusklass_likviidsus_n,
    LiqpCount: year.maakond_likviidsus_protsentiil,
    LiqpSect: year.sektor_likviidsus_protsentiil,
    LiqpSize: year.suurusklass_likviidsus_protsen,
    LVKaK: year.lvkak,
    LVKK: year.lvkk,
    model1y1: prediction.model1y1,
    model1y2: prediction.model1y2,
    model1y3: prediction.model1y3,
    model2y1: prediction.model2y1,
    model2y2: prediction.model2y2,
    model2y3: prediction.model2y3,
    model3y1: prediction.model3y1,
    model3y2: prediction.model3y2,
    model3y3: prediction.model3y3,
    model4y1: prediction.model4y1,
    model4y2: prediction.model4y2,
    model4y3: prediction.model4y3,
    model5y1: prediction.model5y1,
    model5y2: prediction.model5y2,
    model5y3: prediction.model5y3,
    MVK: year.mvk,
    PKM: year.pkm,
    prognAasta: `${year.aasta}`,
    registrikood: year.jykood,
    Ret_n_Count: year.maakond_tasuvus_n,
    Ret_n_Sect: year.sektor_tasuvus_n,
    Ret_n_Size: year.suurusklass_tasuvus_n,
    RetpCount: year.maakond_tasuvus_protsentiil,
    RetpSect: year.sektor_tasuvus_protsentiil,
    RetpSize: year.suurusklass_tasuvus_protsentii,
    RK: year.rk,
    ROA: year.roa,
    ROE: year.roe,
    sektorNo: year.sektor_nr,
    size: year.ettevotte_suurusklass,
    VaKK: year.vakk,
    VK: year.vk,
    VKK: year.vkk,
  };

  return response;
}

export function buildNullResponse(): ApiResponse {
  return {
    registrikood: null,
    model1y1: null,
    model1y2: null,
    model1y3: null,
    model2y1: null,
    model2y2: null,
    model2y3: null,
    model3y1: null,
    model3y2: null,
    model3y3: null,
    model4y1: null,
    model4y2: null,
    model4y3: null,
    model5y1: null,
    model5y2: null,
    model5y3: null,
    prognAasta: null,
    EMTAK: null,
    sektorNo: null,
    size: null,
    county: null,
    kov: null,
    hoiv: null,
    LVKK: null,
    MVK: null,
    RK: null,
    VaKK: null,
    LVKaK: null,
    VKK: null,
    VK: null,
    KOS: null,
    IKK: null,
    AKM: null,
    PKM: null,
    ROA: null,
    ROE: null,
    TJT: null,
    EffpSect: null,
    Eff_n_Sect: null,
    EffpSize: null,
    Eff_n_Size: null,
    EffpCount: null,
    Eff_n_Count: null,
    LiqpSect: null,
    Liq_n_Sect: null,
    LiqpSize: null,
    Liq_n_Size: null,
    LiqpCount: null,
    Liq_n_Count: null,
    LevpSect: null,
    Lev_n_Sect: null,
    LevpSize: null,
    Lev_n_Size: null,
    LevpCount: null,
    Lev_n_Count: null,
    RetpSect: null,
    Ret_n_Sect: null,
    RetpSize: null,
    Ret_n_Size: null,
    RetpCount: null,
    Ret_n_Count: null,
    EmppSect: null,
    Emp_n_Sect: null,
    EmppSize: null,
    Emp_n_Size: null,
    EmppCount: null,
    Emp_n_Count: null,
  };
}
