import { ApiResponse, PredictionResponse } from "../domain/index";
import { CompanyYear, Company } from "../infrastructure/models";

interface BuildResponseParams {
  prediction: PredictionResponse;
  regNr: string;
  companyYear: CompanyYear;
  company: Company;
}

export function buildSuccess(params: BuildResponseParams) {
  const company = params.companyYear.company;
  return {
    registrikood: params.regNr,
    model1y1: params.prediction.model1y1,
    model1y2: params.prediction.model1y2,
    model1y3: params.prediction.model1y3,
    model2y1: params.prediction.model2y1,
    model2y2: params.prediction.model2y2,
    model2y3: params.prediction.model2y3,
    model3y1: params.prediction.model3y1,
    model3y2: params.prediction.model3y2,
    model3y3: params.prediction.model3y3,
    model4y1: params.prediction.model4y1,
    model4y2: params.prediction.model4y2,
    model4y3: params.prediction.model4y3,
    model5y1: params.prediction.model5y1,
    model5y2: params.prediction.model5y2,
    model5y3: params.prediction.model5y3,
    prognAasta: params.companyYear.yearNumber,
    EMTAK: company.emtak,
    sektorNo: company.sektor_nr,
    // Algses "dokumentatsioonis" on size_min, size_max, mis on kuidagi string'i kombineeritud
    // näide: 1)_1_kuni_9
    size: null,
    county: company.maakond,
    kov: company.kov,
    // mis see on? uus värk
    hoiv: null,
    // ei leia kuskilt, kuigi pole uus
    LVKK: null,
    // sama mis eelmine
    RK: null,
    // ... dokumenteerige kõik, kus on 'null' väärtus allpool
    VaKK: null,
    LVKaK: null,
    VKK: null,
    VK: null,
    KOS: null,
    IKK: null,
    AKM: null,
    PKM: null,
    ROA: null,
    ROE: null,
    TJT: null,
    EffpSect: company.sektor_efektiivsus_protsentiil,
    EffpSize: company.suurusklass_efektiivsus_protse,
    EffpCount: company.maakond_efektiivsus_protsentii,
    LiqpSect: company.sektor_likviidsus_protsentiil,
    LiqpSize: company.suurusklass_likviidsus_n,
    LiqpCount: company.maakond_likviidsus_protsentiil,
    RetpSect: company.sektor_tasuvus_n,
    RetpSize: company.suurusklass_tasuvus_protsentii,
    RetpCount: company.maakond_tasuvus_protsentiil,
    // Tooviljakuse_kasv - kust see tuleb (uus asi)
    EmppSect: null,
    EmppSize: company.suurusklass_efektiivsus_protse,
    EmppCount: company.maakond_efektiivsus_protsentii,
    Eff_n_Size: null,
    Eff_n_Sect: null,
    Eff_n_Count: null,
    Liq_n_Sect: null,
    Liq_n_Size: null,
    Liq_n_Count: null,
    LevpSect: null,
    Lev_n_Sect: null,
    LevpSize: null,
    Lev_n_Size: null,
    LevpCount: null,
    Lev_n_Count: null,
    Ret_n_Sect: null,
    Ret_n_Size: null,
    Ret_n_Count: null,
    Emp_n_Sect: null,
    Emp_n_Size: null,
    Emp_n_Count: null,
  };
}

export function buildNullResponse(): ApiResponse {
  return {
    registrikood: null,
    model1y1: null,
    model1y2: null,
    model1y3: null,
    model2y1: null,
    model2y2: null,
    model2y3: null,
    model3y1: null,
    model3y2: null,
    model3y3: null,
    model4y1: null,
    model4y2: null,
    model4y3: null,
    model5y1: null,
    model5y2: null,
    model5y3: null,
    prognAasta: null,
    EMTAK: null,
    sektorNo: null,
    size: null,
    county: null,
    kov: null,
    hoiv: null,
    LVKK: null,
    MVK: null,
    RK: null,
    VaKK: null,
    LVKaK: null,
    VKK: null,
    VK: null,
    KOS: null,
    IKK: null,
    AKM: null,
    PKM: null,
    ROA: null,
    ROE: null,
    TJT: null,
    EffpSect: null,
    Eff_n_Sect: null,
    EffpSize: null,
    Eff_n_Size: null,
    EffpCount: null,
    Eff_n_Count: null,
    LiqpSect: null,
    Liq_n_Sect: null,
    LiqpSize: null,
    Liq_n_Size: null,
    LiqpCount: null,
    Liq_n_Count: null,
    LevpSect: null,
    Lev_n_Sect: null,
    LevpSize: null,
    Lev_n_Size: null,
    LevpCount: null,
    Lev_n_Count: null,
    RetpSect: null,
    Ret_n_Sect: null,
    RetpSize: null,
    Ret_n_Size: null,
    RetpCount: null,
    Ret_n_Count: null,
    EmppSect: null,
    Emp_n_Sect: null,
    EmppSize: null,
    Emp_n_Size: null,
    EmppCount: null,
    Emp_n_Count: null,
  };
}
